# Generated by Django 2.2 on 2019-11-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamanho', '0002_auto_20191128_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamanho',
            old_name='tamanho',
            new_name='nome',
        ),
    ]
