# Generated by Django 2.2 on 2019-11-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabores',
            name='tempo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sabores',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
